name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}          

    - name: Clone Project & Dependencies
      run: |
        rm -rf ~/proxy-forwarder-node
        git clone git@github.com:mathiasklenk/proxy-forwarder-node.git
        cd ~/proxy-forwarder-node
        npm install 

    - name: Set Environment Variables
      run: |
        touch .env
        echo PORT =${{ secrets.PORT }} >> .env
        echo API_SERVICE_URL =${{ secrets.API_SERVICE_URL }} >> .env
    
    - name: Start Application
      run: |
        npm start
