name: Node Github CI

on:
  push:
    branches:
      - main
      
env: 
  PORT: ${{secrets.PORT}} 
  API_SERVICE_URL: ${{secrets.API_SERVICE_URL}} 

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        
        script: |
          cd ~/proxy-forwarder-node
          git pull origin main
          npm install 
          npm start
