name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        
        script: |
          cd ~/proxy-forwarder-node
          git pull origin main
          npm install 
          npm start
